version: "3"
services:
    db:
        environment:
            - "MYSQL_DATABASE=pterodactyl"
            - "MYSQL_PASSWORD=pterodactyl"
            - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
            - "MYSQL_USER=pterodactyl"
        image: mariadb:latest
        networks:
            - default
        volumes:
            - db:/var/lib/mysql
    http:
        build:
            context: services/http
            dockerfile: Dockerfile
        depends_on:
            - "php"
        ports:
            - "80:80"
        networks:
            - default
        volumes:
            - env:/var/www/html/env
            - panel:/var/www/html/pterodactyl
            - storage:/var/www/html/pterodactyl/storage
    php:
        build:
            context: services/php
            dockerfile: Dockerfile
        depends_on:
            - "db"
        networks:
            - default
        volumes:
            - env:/var/www/html/env
            - panel:/var/www/html/pterodactyl
            - storage:/var/www/html/pterodactyl/storage
    redis:
        image: redis:alpine
        networks:
            - default

networks:
    default:
        driver: bridge

volumes:
    db:
    env:
    panel:
    storage:
